# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c27249a555ea2b48d23860ce692f0767c39ecd5072cd9fb09e7dd776ff0aca464a05d1f8369e95b0dc5f7e1e7c2ebfdb349e8106d7d0d70355c3f6df4816b59

test:
  secret_key_base: e87c36198d26f547e5b6e5c99d55c88cea8bfa7082359317d9bd33fa266334a8079f744ef790644a2e4bcc8e03bdf3a0151cd2f595cd775190eedde6950eb68d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
